timezone: "Europe/Berlin"

paginate: 5

gems: [jekyll-paginate]
paginate_path: "blog/:num"

name: ramsesoriginal

rssbaseurl: https://ramsesoriginal.github.io

date_format: "%d. %m. %Y"
time_format: "%H:%M:%S"

url: "https://ramsesoriginal.github.io"
#url: "http://localhost:4000"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Ramsesoriginal"
